version: '3'
services:
  postgres:
    image: 'postgres:14.1-alpine'
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: fx_transactions_development
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db: {}
